"""add link_type to links

Revision ID: 363419dae104
Revises: 001_add_order_fields
Create Date: 2026-06-28 20:07:12.069634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '363419dae104'
down_revision = '001_add_order_fields'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link_type', sa.String(length=20), server_default='custom', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('links', schema=None) as batch_op:
        batch_op.drop_column('link_type')

    # ### end Alembic commands ###
