"""Add card_colour, card_border, card_font columns

Revision ID: 789b5f349ce2
Revises: 004_add_pdf_r2_key
Create Date: 2026-07-12 12:23:27.007418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '789b5f349ce2'
down_revision = '004_add_pdf_r2_key'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('card_colour', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('card_border', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('card_font', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('card_font')
        batch_op.drop_column('card_border')
        batch_op.drop_column('card_colour')

    # ### end Alembic commands ###
