EXAMPLE_PROFILES = [
    {
        'id': 'spark-and-sons',
        'category': 'trades',
        'short_name': 'Spark & Sons',
        'type': 'Electrician',
        'brand_name': 'Spark & Sons Electrical',
        'tagline': 'Reliable electrical work across Leeds',
        'initials': 'SS',
        'links': [
            ('website', 'Website'), ('whatsapp', 'WhatsApp'), ('phone', 'Call'),
            ('email', 'Email'), ('custom', 'Customer reviews'),
        ],
        'why_heading': 'Turn an introduction into a booked job',
        'why_text': 'Put urgent contact routes first, then give customers somewhere to check the business and its work.',
        'points': ['Call and WhatsApp are immediately available', 'Website and reviews add reassurance', 'Useful after a referral or site visit'],
    },
    {
        'id': 'willow-street',
        'category': 'small-business',
        'short_name': 'Willow Street',
        'type': 'Bakery',
        'brand_name': 'Willow Street Bakery',
        'tagline': 'Bread · Pastries · Coffee',
        'initials': 'WB',
        'links': [
            ('website', 'Website'), ('instagram', 'Instagram'), ('custom', "Today's menu"),
            ('custom', 'Find us'), ('email', 'Email'),
        ],
        'why_heading': 'Make a local visit effortless',
        'why_text': 'Opening information, directions and ordering matter more to a local customer than a long company description.',
        'points': ['Menu and directions answer practical questions', 'Instagram supports repeat discovery', 'Every link stays easy to update'],
    },
    {
        'id': 'maya-creates',
        'category': 'creators',
        'short_name': 'Maya Creates',
        'type': 'Content creator',
        'brand_name': 'Maya Creates',
        'tagline': 'Style · City guides · Creative ideas',
        'initials': 'MC',
        'links': [
            ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('custom', 'YouTube'),
            ('custom', 'Media kit'), ('email', 'Collaborate with me'),
        ],
        'why_heading': 'Make collaborations easier to start',
        'why_text': 'Bring social channels and commercial information into one branded destination without adding another app.',
        'points': ['The media kit is easy for brands to find', 'Social channels stay together', 'Email provides a direct collaboration route'],
    },
    {
        'id': 'train-with-jordan',
        'category': 'professionals',
        'short_name': 'Train with Jordan',
        'type': 'Personal trainer',
        'brand_name': 'Train with Jordan',
        'tagline': 'Strength · Movement · Lasting habits',
        'initials': 'TJ',
        'links': [
            ('custom', 'Book a consultation'), ('website', 'Coaching options'),
            ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('email', 'Email'),
        ],
        'why_heading': 'Move interest directly into a booking',
        'why_text': 'Lead with the next commercial step while leaving space for prospects to understand the coaching offer.',
        'points': ['Booking is the first destination', 'Packages remain one tap away', 'WhatsApp handles quick questions'],
    },
    {
        'id': 'north-and-co',
        'category': 'professionals',
        'short_name': 'North & Co',
        'type': 'Creative studio',
        'brand_name': 'North & Co Studio',
        'tagline': 'Brand identity · Digital design',
        'initials': 'NC',
        'links': [
            ('custom', 'Selected work'), ('website', 'Website'),
            ('custom', 'Services & availability'), ('instagram', 'Instagram'), ('email', 'Start a project'),
        ],
        'why_heading': 'Let the work lead the conversation',
        'why_text': 'A portfolio-first order reflects how creative clients decide whether a studio is right for them.',
        'points': ['Selected work receives priority', 'Availability sets expectations', 'The enquiry route stays clear'],
    },
    {
        'id': 'amina-rahman',
        'category': 'professionals',
        'short_name': 'Amina Rahman',
        'type': 'Consultant',
        'brand_name': 'Amina Rahman Consulting',
        'tagline': 'Clearer operations for growing teams',
        'initials': 'AR',
        'links': [
            ('linkedin', 'LinkedIn'), ('custom', 'Book an introduction'),
            ('custom', 'Experience & credentials'), ('website', 'Website'), ('email', 'Email'),
        ],
        'why_heading': 'Build professional credibility without clutter',
        'why_text': 'Credentials, LinkedIn and a booking route give a new contact enough context to take the next step.',
        'points': ['LinkedIn adds professional context', 'Credentials build confidence', 'Booking turns interest into action'],
    },
]

EXAMPLE_FAQS = [
    ('Are these real CardBranch customers?', 'No. Every profile on this page is a fictional example created to show how different businesses could arrange their links.'),
    ('Can I choose which links appear first?', 'Yes. Arrange the page around the action you most want a new contact to take, such as calling, booking, visiting your website or viewing your work.'),
    ('Can I update the links later?', 'Yes. The hosted CardBranch address and QR code stay the same while you update the links displayed on the page.'),
    ('Do visitors need an app?', 'No. A CardBranch page opens in a normal web browser from its link or QR code.'),
]
